name: flutter_diffusion
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_archive: ^5.0.0
  get: ^4.6.5
  http: ^1.1.0
  image: ^4.0.17
  intl: ^0.18.1
  path_provider: ^2.0.15
  share: ^2.0.4
  tflite_flutter:
    git: https://github.com/tensorflow/flutter-tflite

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true

